- platform: gpio
  pin: GPIO11
  id: a
  filters:
    - settle: 10ms
  on_press: 
    then:
      - script.execute: wakeup_button
    
- platform: gpio
  pin: GPIO12
  id: b
  filters:
    - settle: 10ms
  on_press: 
    then:
      - script.execute: wakeup_button

- platform: gpio
  pin: GPIO38
  id: x
  filters:
    - settle: 10ms
  on_press: 
    then:
      - script.execute: wakeup_button

- platform: gpio
  pin: GPIO47
  id: o
  filters:
    - settle: 10ms
  on_click: 
    - min_length: 10ms
      max_length: 500ms
      then:
        - light.toggle:
            id: backlight
            transition_length: 0.5s
        - delay: 100ms  
        - lambda: id(is_sleeping)=!id(is_sleeping);
        - lvgl.animimg.start: ani_battery_charging
        - if:
            condition:
              lambda: 'return id(is_sleeping);'
            then:
              - lvgl.pause:
                  show_snow: false
                  lvgl_id: lvgl_1
              - lvgl.animimg.stop: ani_battery_charging
    - min_length: 500ms
      max_length: 2000ms
      then:
        - lvgl.page.show: 
            id: page_main
            animation: FADE_IN
            time: 500ms