esphome:
  name: sdl

host:
  mac_address: "06:35:69:ab:f6:79"

display:
  - platform: sdl
    show_test_card: false
    dimensions:
      width: 320
      height: 240

substitutions:
  lemonade_version: "1.0.2-rc1 Canary"

logger:
  level: DEBUG

touchscreen:
  platform: sdl
  id: touch_panel

packages:
  - !include packages/host-test/lvgl.yaml
  - !include packages/host-test/script.yaml
  - !include packages/host-test/message-lvgl.yaml
  - !include packages/s3_touch/features/message/message-resource.yaml
  - !include packages/resources.yaml
  - !include packages/s3_touch/games/limbus_prescript/prescript.yaml
