substitutions:
  # 基本信息
  lemonade_board: "um_pros3"
  lemonade_device_name: "lemonade"
  lemonade_device_friendly_name: "Lemonade"
  lemonade_version: "0.6.0-rc1"
  lemonade_ota_password: !secret ota_password
  lemonade_ibeacon_uuid: "c2c77f58-9876-4a2a-a43d-dcb5ab317fae"
  lemonade_ibeacon_major: "987"
  lemonade_ibeacon_minor: "114"
  lemonade_ibeacon_measured_power: "-59"
  lemonade_ota_md5_url: ***REMOVED***lemonade/ota/lemonade.md5
  lemonade_ota_url: ***REMOVED***lemonade/ota/firmware.ota.bin

  zsv_iot_url: http://iot.zsvstudio.top/

external_components:
  - source: github://cookie987/esphome-custom-components

packages:
  # 核心组件
  - !include packages/lemonade.yaml
  - !include packages/lvgl.yaml
  - !include packages/hardware.yaml
  - !include packages/script.yaml
  - !include packages/interval.yaml
  - !include packages/resources.yaml
  - !include packages/networks.yaml
  # 游戏
  - !include packages/games/game_core.yaml
  # 其他组件
  - !include packages/features/weather-forecast.yaml

