substitutions:
  # 基本信息
  lemonade_board: "um_pros3"
  lemonade_device_name: "lemonade"
  lemonade_device_friendly_name: "Lemonade"
  lemonade_version: "0.5.0-rc1"
  lemonade_ota_password: !secret ota_password

external_components:
  - source: github://cookie987/esphome-custom-components

packages:
  # 核心组件
  - !include packages/lemonade.yaml
  - !include packages/lvgl.yaml
  - !include packages/hardware.yaml
  - !include packages/script.yaml
  - !include packages/interval.yaml
  - !include packages/resources.yaml

  # 其他组件
  - !include packages/features/weather-forecast.yaml