# ESP32S3 触摸

esphome:
  project:
    name: "cookie987.lemonade"
    version: "1.4.0"
  name_add_mac_suffix: true

substitutions:
  # 基本信息
  lemonade_board: "um_pros3"
  lemonade_device_name: "lemonade-t"
  lemonade_device_friendly_name: "Lemonade"
  lemonade_device_model: "智能时钟_T"
  lemonade_version: "1.4.0 Public"
  lemonade_ota_password: !secret ota_password
  lemonade_ibeacon_uuid: "c2c77f58-9876-4a2a-a43d-dcb5ab317fae"
  lemonade_ibeacon_major: "987"
  lemonade_ibeacon_minor: "114"
  lemonade_ibeacon_measured_power: "-59"
  lemonade_ota_md5_url: ***REMOVED***lemonade/s3-touch/lemonade.md5
  lemonade_ota_url: ***REMOVED***lemonade/s3-touch/firmware.ota.bin
***REMOVED***  log_level: WARN

esp32_ble_beacon: !remove

external_components:
  - source: components

packages:
  # 核心组件
  - !include packages/s3_touch/lemonade.yaml
  - !include packages/s3_touch/lvgl.yaml
  - !include packages/s3_touch/hardware.yaml
  - !include packages/s3_touch/script.yaml
  - !include packages/s3_touch/interval.yaml
  - !include packages/resources.yaml
  - !include packages/s3_touch/networks.yaml
  - !include packages/s3_touch/features/mqtt_handler.yaml
  # - !include packages/storage.yaml
  # 设置
  - !include packages/s3_touch/features/setting/setting.yaml
  # 秒表
  - !include packages/s3_touch/features/timer/timer.yaml
  # 游戏
  # - !include packages/games/game_core.yaml
  # 天气与日历
  - !include packages/s3_touch/features/weather/weather.yaml
  # 聊天
  - !include packages/s3_touch/features/message/message.yaml
