# ESP32S3 无触摸

esphome:
  project:
    name: "cookie987.lemonade"
    version: "1.0.0"
  name_add_mac_suffix: false

substitutions:
  # 基本信息
  lemonade_board: "um_pros3"
  lemonade_device_name: "lemonade"
  lemonade_device_friendly_name: "Lemonade"
  lemonade_device_model: "智能时钟_C"
  lemonade_version: "1.0.0-rc1 Canary"
  lemonade_ota_password: !secret ota_password
  lemonade_ibeacon_uuid: "c2c77f58-9876-4a2a-a43d-dcb5ab317fae"
  lemonade_ibeacon_major: "987"
  lemonade_ibeacon_minor: "114"
  lemonade_ibeacon_measured_power: "-59"
  lemonade_ota_md5_url: ***REMOVED***lemonade/ota/lemonade.md5
  lemonade_ota_url: ***REMOVED***lemonade/ota/firmware.ota.bin

***REMOVED***  zsv_iot_url: ***REMOVED***zsv/
  c987_iot_url: ***REMOVED***api/

external_components:
  - source: github://cookie987/esphome-custom-components
    components: [git_commit_sha, power_management]

esp32_ble_beacon: !remove

packages:
  # 核心组件
  - !include packages/s3/lemonade.yaml
  - !include packages/s3/lvgl.yaml
  - !include packages/s3/hardware.yaml
  - !include packages/s3/script.yaml
  - !include packages/s3/interval.yaml
  - !include packages/resources.yaml
  - !include packages/s3/networks.yaml
  # - !include packages/storage.yaml
  # 游戏
  - !include packages/s3/games/game_core.yaml
  # 其他组件
  - !include packages/s3/features/weather-forecast/weather.yaml
  - !include packages/s3/features/calendar/calendar.yaml

