esphome:
  project:
    name: "cookie987.lemonade"
    version: "0.6.1"
  name_add_mac_suffix: true

substitutions:
  # 基本信息
  lemonade_board: "um_pros3"
  lemonade_device_name: "lemonade"
  lemonade_device_friendly_name: "Lemonade"
  lemonade_version: "0.6.1 Stable"
  lemonade_ota_password: !secret ota_password

  lemonade_ota_md5_url: ***REMOVED***lemonade/ota/public/lemonade.md5
  lemonade_ota_url: ***REMOVED***lemonade/ota/public/firmware.ota.bin

  zsv_iot_url: ***REMOVED***zsv/
  c987_iot_url: ***REMOVED***api/

esp32_ble_beacon: !remove

external_components:
  - source: github://cookie987/esphome-custom-components

packages:
  # 核心组件
  - !include packages/lemonade.yaml
  - !include packages/lvgl.yaml
  - !include packages/hardware.yaml
  - !include packages/script.yaml
  - !include packages/interval.yaml
  - !include packages/resources.yaml
  - !include packages/networks.yaml
  # 游戏
  - !include packages/games/game_core.yaml
  # 其他组件
  # - !include packages/features/weather-forecast/core.yaml

