esphome:
  name: bugtest
  friendly_name: bugtest
  platformio_options:
    build_flags:
      -DCONFIG_PM_ENABLE=1
      -DCONFIG_FREERTOS_USE_TICKLESS_IDLE=1
      -DCONFIG_FREERTOS_IDLE_TIME_BEFORE_SLEEP=3

  includes:
    # - <esp_littlefs.h>
    - <mbedtls/base64.h>
    - <fstream>


esp32:
  board: um_pros3
  cpu_frequency: 240MHz
  flash_size: 16MB
  partitions: partitions_16M.csv
  framework:
    type: esp-idf
    # components:
    #   - name: joltwallet/littlefs
    #     source: https://github.com/joltwallet/esp_littlefs.git
    advanced:
      execute_from_psram: yes
    sdkconfig_options:
      CONFIG_PM_ENABLE: y
      CONFIG_PM_DFS_INIT_AUTO: y

external_components:
  - source: github://cookie987/esphome-custom-components
    components: [git_commit_sha, power_management]

  - source: github://p1ngb4ck/esphome@dev
    components: [binary_storage, picture_viewer, storage, webdav_server, usb_host, usb_uart, usb_storage]

binary_storage:
  - type: flash_partition
    id: littlefs
    partition_label: littlefs
    mount_path: /data

psram:
  mode: octal
  speed: 80MHz

web_server_base:

wifi:
  reboot_timeout: 0s
  enable_btm: true
  enable_rrm: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lemonade"
    password: "Lemonade"
    ap_timeout: 0s
  power_save_mode: HIGH

storage:
  id: storage_id
  # mounts:
  #   - path: /data
  #     platform: binary_storage
  #     id: littlefs_storage

webdav_server:
  id: webdav_sdcard
  storage_id: storage_id
  root_path: "/data"
  url_prefix: "/"
  port: 81
  username: "admin"
  password: "123456"

usb_host:
  id: usb_host_id
  enable_hubs: True
  max_transfer_requests: 16
usb_storage:
  id: usb_storage_id
  devices:
    - id: usb_storage_30gb
      mount_path: "/usb"
      vid: 0
      pid: 0