# ESP32S3 触摸

esphome:
  project:
    name: "cookie987.lemonade"
    version: "1.9.1"
  name_add_mac_suffix: false

substitutions:
  # 基本信息
  lemonade_board: "um_pros3"
  lemonade_device_name: "lemonade-tc32"
  lemonade_device_friendly_name: "Lemonade"
  lemonade_device_model: "智能时钟_T_3.2"
  lemonade_version: "1.9.1 Canary"
  lemonade_ota_password: !secret ota_password
  lemonade_app_store_index_url: !secret app_store_index_url
  lemonade_ibeacon_uuid: "c2c77f58-9876-4a2a-a43d-dcb5ab317fae"
  lemonade_ibeacon_major: "987"
  lemonade_ibeacon_minor: "114"
  lemonade_ibeacon_measured_power: "-59"
  lemonade_update_info_url: !secret update_info_url_t32_canary
  lemonade_app_platform: "s3_t_3_2"
  c987_mqtt_server: !secret mqtt_server
  c987_mqtt_register_url: !secret mqtt_register_url
  log_level: DEBUG
  battery_warning_temp: 55.0
  battery_low_temp: 50.0

external_components:
  - source: components

api:
  reboot_timeout: 0s

esp32_ble_beacon: !remove

packages:
  # 核心组件
  - !include packages/s3_touch/lemonade.yaml
  - !include packages/s3_touch/lvgl.yaml
  - !include packages/s3_touch_3.2/hardware.yaml
  # - !include packages/s3_touch_3.2/audio_hardware.yaml
  - !include packages/s3_touch/script.yaml
  - !include packages/s3_touch/interval.yaml
  - !include packages/resources.yaml
  - !include packages/s3_touch/networks.yaml
  - !include packages/s3_touch/features/mqtt_handler.yaml
  - !include packages/s3_touch/features/mqtt_credentials.yaml

  # - !include packages/storage.yaml
  # 设置
  - !include packages/s3_touch/features/setting/setting.yaml
  - !include packages/s3_touch/features/security/security.yaml
  - !include packages/s3_touch/features/app_store/app_store.yaml
  # 秒表
  - !include packages/s3_touch/features/timer/timer.yaml
  # 天气与日历
  - !include packages/s3_touch/features/weather/weather.yaml
  # 聊天
  - !include packages/s3_touch/features/message/message.yaml
