packages:
  - !include message-lvgl.yaml
  - !include message-resource.yaml
  - !include message-shortcode.yaml
  - !include message-mqtt_handler.yaml

esphome:
  on_boot:
    - priority: 100
      then:
        - script.execute: message_public_listen
        - script.execute: message_mqtt_handler

script:
  - id: send_message
    then:
      - lambda: |-
          uint16_t tab_act = lv_tabview_get_tab_act(tabview_message);
          std::string targetuid = std::string(lv_textarea_get_text(textarea_message_username_input));
          ESP_LOGD("Chat", "Target UID: %s", targetuid.c_str());
          // 要发送的消息内容
          std::string message_content;
          switch (tab_act) {
            case 1:
              message_content = lv_textarea_get_text(textarea_message_friend_input);
              break;
            case 2:
              message_content = lv_textarea_get_text(textarea_message_public_input);
              break;
            default:
              break;
          }
          
          // 处理短代码
          // eg /hd/ 将被替换为好的
          std::string text = message_content;
          size_t pos = 0;
          while (pos < text.length()) {
              size_t start = text.find('/', pos);
              if (start == std::string::npos) break;
              size_t end = text.find('/', start + 1);
              if (end == std::string::npos) break;
              // 提取 "/abc/"
              std::string shortcode = text.substr(start, end - start + 1);
              std::string value = id(message_shortcode)[shortcode];
              if (!value.empty()) {
                  text.replace(start, shortcode.length(), value);
                  pos = start + value.length();
              } else {
                  // 不认识的 shortcode，跳过这个 '/'
                  pos = start + 1;
              }
          }
          message_content = text;
          std::string mac = id(text_sensor_mac_address).state;
          switch (tab_act) {
            case 0:
              break;
            case 1:
              id(mqtt_client).publish_json((std::string("chat/") +
                                            mac +
                                            std::string("/up")).c_str(),
                                            [=](JsonObject root) {
                root["type"] = "p2p";
                root["to"] = targetuid;
                root["content"] = message_content;
                root["msg_id"] = esp_random();
              });
              lv_textarea_set_text(textarea_message_friend_input, "");
              ESP_LOGD("Chat", "Sent message to %s", targetuid.c_str());
              break;
            case 2:
              id(mqtt_client).publish("smck/glousr",(
                                        id(uid) +
                                        std::string(":") +
                                        message_content
                                      ).c_str()
                        );
              lv_textarea_set_text(textarea_message_public_input, "");
              ESP_LOGD("Chat", "Sent message to the topic");
              break;
            default:
              break;
          }
          

  - id: message_public_listen
    then:
      - lambda: |-
          id(mqtt_client).subscribe("smck/glousr", [=](const std::string &topic, const std::string &payload) {
              ESP_LOGD("Chat", "Got raw public chat message.");
              // 获取发送者
              size_t pos = payload.find(':');
              std::string sender, content;
              if (pos != std::string::npos) {
                  sender  = payload.substr(0, pos);
                  content = payload.substr(pos + 1);
              } else {
                  sender  = payload;
                  content = "";
              }
              // 获取当前时间
              auto t = id(ntp_time).now();
              lv_list_add_text(id(list_message_public),
                                (
                                  std::string(t.strftime("%Y-%m-%d %H:%M:%S")) +
                                  std::string(" · ") +
                                  sender // +
                                  // std::string(": ")
                                ).c_str()
                              );
              lv_obj_t * list_btn = lv_list_add_btn(list_message_public, NULL, content.c_str());
              // 只保留最近的100条
              uint32_t children_count = lv_obj_get_child_cnt(list_message_public);
              if (children_count > 100) {
                for (uint32_t i = 0; i < children_count - 100; i++) {
                  lv_obj_del(lv_obj_get_child(list_message_public, 0));
                }
              }
              lv_obj_scroll_to_view(list_btn, LV_ANIM_ON);
          });