# ESP32S3 无触摸

esphome:
  name: "${lemonade_device_name}"
  friendly_name: ${lemonade_device_friendly_name}
  on_boot:
    then:
      - light.turn_on:
          id: backlight
          transition_length: 1s
      - lambda: |-
          float b = id(backlight).current_values.get_brightness();
          lv_slider_set_value(id(backlight_slider), b * 50.0, LV_ANIM_ON);
          
esp32:
  board: ${lemonade_board}
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    advanced:
      execute_from_psram: true

psram:
  mode: octal
  speed: 80MHz

# captive_portal:

debug:
  update_interval: 5s

globals:
  - id: is_sleeping
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: is_slider_changing
    type: bool
    restore_value: no
    initial_value: "false"
  - id: is_timer_running
    type: bool
    # restore_value: yes
    initial_value: 'false'
  - id: stopwatch_start_time
    type: unsigned long
    restore_value: yes
    initial_value: '0'
  - id: stopwatch_paused_time
    type: unsigned long
    restore_value: yes
    initial_value: '0'
  - id: is_countdown_running
    type: bool
    restore_value: yes
    initial_value: 'false'
  - id: countdown_end_time
    type: unsigned long
    restore_value: yes
    initial_value: '0'
  - id: countdown_hours
    type: int
    restore_value: yes
    initial_value: '0'
  - id: countdown_minutes
    type: int
    restore_value: yes
    initial_value: '0'
  - id: countdown_seconds
    type: int
    restore_value: yes
    initial_value: '0'

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s
  encryption:
    key: "GZV94t0Ynjcna4aoilVTHjhliknuxp8cK9elyuShrKs="

ota:
  - platform: esphome
    password: ${lemonade_ota_password}
    on_begin:
      - output.set_level:
          id: backlight_pin
          level: 100%

  - platform: http_request
    on_begin:
      - output.set_level:
          id: backlight_pin
          level: 100%
    
update:
  - platform: http_request
    name: Firmware Update
    source: http://iot.cookie987.top/lemonade/manifest.json

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: "19"
    password: "88888888"
  - ssid: "SEEWO"
    password: "SEEWOSEEWO"
  reboot_timeout: 0s
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lemonade"
    password: "Lemonade"
  power_save_mode: HIGH


time:
  - platform: sntp
    id: ntp_time
    timezone: "Asia/Shanghai"   # 可改为你所在时区
    servers:
      - 39.101.78.82
      - cn.pool.ntp.org
    on_time_sync: 
      then:
        - lambda: |-
            // 初始化秒表状态（仅在没有保存的状态时）
            static bool initialized = false;
            if (!initialized) {
              initialized = true;
              // 如果没有有效的保存状态，则初始化为默认值
              if (id(stopwatch_start_time) == 0 && id(stopwatch_paused_time) == 0) {
                id(stopwatch_start_time) = millis();
                id(stopwatch_paused_time) = 0;
              }
              unsigned long elapsed = millis() - id(stopwatch_start_time);
              int hours = (elapsed / 1000) / 3600;
              int minutes = ((elapsed / 1000) / 60) % 60;
              int seconds = (elapsed / 1000) % 60;
              int hundredths = (elapsed % 1000) / 10;  // 精确到0.01秒
              char buf[16];
              sprintf(buf, "%02d:%02d:%02d.%02d", hours, minutes, seconds, hundredths);
              // lv_label_set_text(id(stopwatch_label), buf);
              // 初始化倒计时状态
              if (id(countdown_end_time) > 0 && id(is_countdown_running)) {
                // 如果倒计时正在运行且未结束，则继续倒计时
                unsigned long current_time = millis();
                lv_label_set_text(id(lbl_countdown_button), "暂停");
                if (current_time >= id(countdown_end_time)) {
                  // 如果倒计时已经结束，重置状态
                  id(is_countdown_running) = false;
                  id(countdown_end_time) = 0;
                }
              }
              unsigned long current_time = millis();
              if (current_time < id(countdown_end_time)) {
                // 计算剩余时间
                unsigned long remaining = (id(countdown_end_time) - current_time) / 1000;
                
                // 计算小时、分钟、秒
                int hours = remaining / 3600;
                int minutes = (remaining % 3600) / 60;
                int seconds = remaining % 60;
                
                // 更新roller显示
                lv_roller_set_selected(id(roller_countdown_hours_tens).obj, hours / 10, LV_ANIM_ON);
                lv_roller_set_selected(id(roller_countdown_hours_ones).obj, hours % 10, LV_ANIM_ON);
                lv_roller_set_selected(id(roller_countdown_minutes_tens).obj, minutes / 10, LV_ANIM_ON);
                lv_roller_set_selected(id(roller_countdown_minutes_ones).obj, minutes % 10, LV_ANIM_ON);
                lv_roller_set_selected(id(roller_countdown_seconds_tens).obj, seconds / 10, LV_ANIM_ON);
                lv_roller_set_selected(id(roller_countdown_seconds_ones).obj, seconds % 10, LV_ANIM_ON);
                
              }
            }
        
sensor: 
  - platform: wifi_signal
    id: rssi
    update_interval: 2s

  - platform: internal_temperature
    id: internal_temp
    update_interval: 2s
    
  - platform: debug
    free:
      id: heap_free
    block:
      id: heap_block
    loop_time:
      id: loop_time
    psram:
      id: psram_free
    cpu_frequency:
      id: cpu_freq

rtttl:
  output: rttl_pin
  id: rtttl_player
  gain: 60%

light:
  - platform: monochromatic
    output: backlight_pin
    name: "Screen Brightness"
    id: backlight
    restore_mode: RESTORE_DEFAULT_ON
    default_transition_length: 0.1s
    on_state:
      then:
        if: 
          condition:
            lambda: 'return !id(is_slider_changing);'
          then:
            - lvgl.slider.update:
                id: backlight_slider
                value: !lambda 'return id(backlight).current_values.get_brightness() * 50.0;'
                animated: true

http_request:

# online_image:
#   - url: "***REMOVED***img/1.png"
#     format: png
#     id: online_image1
#     type: RGB565

#   - url: "***REMOVED***img/2.png"
#     format: png
#     id: online_image2
#     type: RGB565

#   - url: "***REMOVED***img/3.png"
#     format: png
#     id: online_image3
#     type: RGB565


text_sensor:
  - platform: wifi_info
    mac_address:
      id: text_sensor_mac_address
    ssid:
      id: ssid
  - platform: debug
    device:
      id: device_info
    reset_reason:
      id: reset_reason
  - platform: version
    id: esphome_version


select:
  - platform: lvgl
    widget: roller_image
    name: Background Select
    restore_value: True